name: Aggiorna Orari Metro

on:
  schedule:
    - cron: '0 2 * * 1' # Ogni lunedì alle 02:00
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permesso fondamentale per far scrivere il bot sul repo
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: pip install requests pdfplumber

      - name: Esegui lo script
        run: python script.py

      - name: Commit e Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add orari_m2.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Aggiornamento orari_m2.json"
          git push